# Generated by Django 4.1.3 on 2023-02-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date', 'author']},
        ),
    ]
